### ISSUE TITLE
bug with progress bar

### ISSUE THREAD

**Issue by FaZz-cmd** [NevermindNilas/TheAnimeScripter#10]
![image_2024-02-03_185545712](https://github.com/NevermindNilas/TheAnimeScripter/assets/136253755/15c1685d-955a-4926-8cdd-82b0ce4134dd)
[log.txt](https://github.com/NevermindNilas/TheAnimeScripter/files/14152412/log.txt)

**Comment by NevermindNilas** [comment]
ty, I will look at it in a bit.

**Comment by NevermindNilas** [comment]
https://github.com/NevermindNilas/TheAnimeScripter/commit/fd3b2086dfacd1a3da5a33d8a5abd84870ed93dd

Attempted fix until I find a better way to handle this. For now I will close the issue and come back to it later once I find a  more elegant way of handling this.

**Comment by NevermindNilas** [comment]
Should be fixed with this commit

https://github.com/NevermindNilas/TheAnimeScripter/commit/66fb3208d05d3ca57cf05dbd02064233b20e78bf
