### ISSUE TITLE
ffmpeg command not working

### ISSUE THREAD

**Issue by FaZz-cmd** [NevermindNilas/TheAnimeScripter#12]
![Capture d'écran 2024-02-24 221805](https://github.com/NevermindNilas/TheAnimeScripter/assets/136253755/6854905a-1c52-44fc-943e-9b6c125b5e7b)
![image_2024-02-24_222044314](https://github.com/NevermindNilas/TheAnimeScripter/assets/136253755/b200dc81-76e1-4ae6-9378-3ffa257449ce)

**Comment by NevermindNilas** [comment]
Hi, is there a log.txt generated?

**Comment by FaZz-cmd** [comment]
[log.txt](https://github.com/NevermindNilas/TheAnimeScripter/files/14394461/log.txt)

**Comment by NevermindNilas** [comment]
`CUSTOM_ENCODER: `

It seems like the AE interface didn't parse the command properly, weird... it worked last time I checked. Also as a sidenote, pix_fmt is hardcoded in the script, you can add any other encoding options like filters and codecs though.

**Comment by NevermindNilas** [comment]
Fixed with https://github.com/NevermindNilas/TheAnimeScripter/commit/fb804ac4007edc37121754f97591d0490df5c9c5

Will go ahead and close the issue. Thank you for the report :)
