### ISSUE TITLE
ytdlp not working

### ISSUE THREAD

**Issue by renarchi** [NevermindNilas/TheAnimeScripter#14]
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/159624970/87813e4b-08b3-4b0e-9c65-e40c0204b063)

**Comment by NevermindNilas** [comment]
TO DO!

**Comment by NevermindNilas** [comment]
Should be fixed with:
https://github.com/NevermindNilas/TheAnimeScripter/commit/5833e3d9d7b1230e80980e8479a8738050454c77

Thank for the report!
