### ISSUE TITLE
[bug] first run error

### ISSUE THREAD

**Issue by the-liquid-metal** [NevermindNilas/TheAnimeScripter#15]
C:\Users\me>D:\TAS148\main.exe
Traceback (most recent call last):
  File "main.py", line 433, in <module>
TypeError: isfile: path should be string, bytes, os.PathLike or integer, not NoneType
[11268] Failed to execute script 'main' due to unhandled exception!

**Comment by NevermindNilas** [comment]
can you send the generated log.txt file please.

**Comment by NevermindNilas** [comment]
after reading it again, I've noticed that all you did was to run the executable through the terminal?
`C:\Users\me>D:\TAS148\main.exe`

You should head to [Parameters Guide](https://github.com/NevermindNilas/TheAnimeScripter/blob/main/PARAMETERS.MD) and start from there.

**Comment by the-liquid-metal** [comment]
============== Command Line Arguments ==============
E:\TAS148\main.exe

============== Arguments ==============
VERSION: 1.4.8
INPUT: None
OUTPUT: None
INTERPOLATE: False
INTERPOLATE_FACTOR: 2
INTERPOLATE_METHOD: rife
ENSEMBLE: False
UPSCALE: False
UPSCALE_FACTOR: 2
UPSCALE_METHOD: shufflecugan
CUGAN_KIND: no-denoise
CUSTOM_MODEL: 
DEDUP: False
DEDUP_METHOD: ffmpeg
DEDUP_SENS: 35
SAMPLE_SIZE: 32
NT: 1
HALF: True
INPOINT: 0
OUTPOINT: 0
SHARPEN: False
SHARPEN_SENS: 0.5
SEGMENT: False
SCENECHANGE: False
SCENECHANGE_SENS: 50
DEPTH: False
DEPTH_METHOD: small
ENCODE_METHOD: x264
YTDLP: 
YTDLP_QUALITY: False
RESIZE: False
RESIZE_FACTOR: 2
RESIZE_METHOD: bicubic
CUSTOM_ENCODER: 
BUFFER_LIMIT: 50
AUDIO: True
DENOISE: False
DENOISE_METHOD: scunet

============== System Checker ==============
OS Name: Microsoft Windows 10 Home Single Language
CPU: Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz
RAM: 7.793022155761719 GB
Available RAM: 2.715015411376953 GB
Graphics Card: Intel(R) Iris(R) Plus Graphics

============== Arguments Checker ==============
FFMPEG Path: E:\Downloads\TAS148\_internal\src\ffmpeg\ffmpeg.exe
Getting FFMPEG

**Comment by the-liquid-metal** [comment]
I do run in terminal, after doble clicking was failed. The main window was immediately closed.
Is this window app or console app?

**Comment by NevermindNilas** [comment]
Yeah, you've provided it no ``--input`` or any other form of processing. If you are planning on using it through the CLI then head to  the parameters guide linked in my previous comment.

Also, as a sidenote, your PC might be slightly underpowered, you should only utilize the `NCNN` upscaling / interpolating methods.

**Comment by NevermindNilas** [comment]
> I do run in terminal, after doble clicking was failed. The main window was immediately closed. Is this window app or console app?

For now it's a Command Line App which has a User Interface in After Effects. The GUI is planned for release 1.5.0.

**Comment by NevermindNilas** [comment]
I will close the issue for now since it is not really a bug but rather a misunderstanding.

**Comment by the-liquid-metal** [comment]
> For now it's a Command Line App which has a User Interface in After Effects. The GUI is planned for release 1.5.0.

Hopefully it's not too long. Since there are many parameters, the terminal is not a convenient medium to play with, just to get the picture of the app.

**Comment by NevermindNilas** [comment]
I am no UI / UX Designer nor have I ever worked previously with PYQT6 so it will take some time, a couple of days to a few weeks depending on how fast I can learn it. Regardless I am open to PRs.

As for the parameters, they are there for flexibility purposes.
