### ISSUE TITLE
frames not in the flow of time

### ISSUE THREAD

**Issue by Ewillian9** [NevermindNilas/TheAnimeScripter#17]
Hi again
So i got an intersting issue, when interpolating with various settings, frames are placed in the wrong order in the final output (pacing issue?).
Depends on the settings used, sometimes it's fine but here it's obvious at the end of the video.
I can indeed provide more testing of my own to investigate.

[log.txt](https://github.com/NevermindNilas/TheAnimeScripter/files/14731756/log.txt)
[sc6-Re0.5-Int2-635.webm](https://github.com/NevermindNilas/TheAnimeScripter/assets/156851131/9e8237ae-5c68-46df-bd11-7f011512367b)

**Comment by NevermindNilas** [comment]
Multithreadding is experimental. Please set the number of threads to 1 and try again.

**Comment by Ewillian9** [comment]
Okay that worked and i notice no performance degradation.
test in 520p
--nt 12 = 11 fps
--nt 1   = 12 fps

test in 1040p
--nt 12 = 4.3 fps
--nt 1   = 5 fps

**Comment by NevermindNilas** [comment]
considering the fact that you got a 6900xt I would be expecting much higher numbers than that, Upwards of 30-40 to say the least.

Can you run the interpolation by 2x on a 1080p video and send the log.txt over in a new issue?
