### ISSUE TITLE
FPS x2 1080p 6900xt

### ISSUE THREAD

**Issue by Ewillian9** [NevermindNilas/TheAnimeScripter#18]
yep absolutly
i was running svt p3 so my cpu is the bottleneck, if i run default x264 ensemble 0 i'm at 39 fps on 1080p
[log.txt](https://github.com/NevermindNilas/TheAnimeScripter/files/14732040/log.txt)
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/156851131/b81078c7-9446-4057-ab66-08bca17c03d2)

EDIT reaching up to 41 fps with memory oc

**Comment by Ewillian9** [comment]
is there a way to set ncnn threads?

**Comment by Ewillian9** [comment]
Maybe i should open another issue idk, it's not the same topic but i didn't saw the mention of uhd mod for rife. Is it plossible to add a setting for that?

**Comment by NevermindNilas** [comment]
the ncnn threads are tied to the `--nt` variable we discussed earlier, but as u have seen ignoring the frame pacing part there's no innate performance improvements at least with the current implementation.

UHD is auto decided upon by the script with:
```py
UHD = True if new_width >= 3840 or new_height >= 2160 else False
```

**Comment by NevermindNilas** [comment]
The performance of rife is in line with what I expected then, I was a bit fumbled by your results of 5fps but ofc I didn't bother to check the encoding parameters.

**Comment by NevermindNilas** [comment]
Btw, you are more than welcome to join the discord server and share your result in there as well:
https://discord.gg/YFd36w5XjW

**Comment by Ewillian9** [comment]
yeah the 5 fps was svt p3 with 4k source reaching up tp 1gb/s so maybe a bit tough to swallow
