### ISSUE TITLE
Cant import some clips when selecting "interpolate"

### ISSUE THREAD

**Issue by 0izayoi0** [NevermindNilas/TheAnimeScripter#22]
![Screenshot 2024-04-20 131308](https://github.com/NevermindNilas/TheAnimeScripter/assets/98900917/b7416d3c-5b84-4d47-9efe-a89ec039cb39)
![Screenshot 2024-04-20 131325](https://github.com/NevermindNilas/TheAnimeScripter/assets/98900917/b3c55e29-026e-48e1-a316-fa70e35822b7)
[log.txt](https://github.com/NevermindNilas/TheAnimeScripter/files/15047444/log.txt)

**Comment by NevermindNilas** [comment]
Hi,

You are using version 1.4.8 and it is trying to download files that no longer exist. You should upgrade to 1.5.0 and try again.
