### ISSUE TITLE
gui is broken

### ISSUE THREAD

**Issue by renarchi** [NevermindNilas/TheAnimeScripter#23]
https://github.com/NevermindNilas/TheAnimeScripter/assets/159624970/a4e31165-9f86-4937-b853-823f0c707fc0

**Comment by VicMahoney** [comment]
Hello! Will the gui be fixed so that non-professionals in Python (like me) can use the program?

**Comment by NevermindNilas** [comment]
Fixed with https://github.com/NevermindNilas/TheAnimeScripter/releases/tag/v1.7.0

Thank you for the report.
