### ISSUE TITLE
[Bug] - UI elements are not visible in dark mode

### ISSUE THREAD

**Issue by sergiohzph** [NevermindNilas/TheAnimeScripter#25]
Probably this has been alredy reported, but I'll also report it, who knows.

As you can see, the dark mode of the GUI is so bugged, I can't see anything:
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/138529583/c726166d-d9d9-4124-9ef3-42c9f56e8845)
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/138529583/6d84970c-8c88-49d8-a2e5-28e29e9ea516)

**Comment by NevermindNilas** [comment]
Yup, that's a bug that has been reported over on discord. The GUI Will see a [massive overhaul](https://github.com/NevermindNilas/TheAnimeScripter/discussions/13#discussioncomment-8953119) as I find more time and will to work on it.
