### ISSUE TITLE
[Bug] GUI settings not respected, not writing relevant data to settings file either

### ISSUE THREAD

**Issue by CasualDev242** [NevermindNilas/TheAnimeScripter#31]
This was mentioned before in a Closed Issue, and marked as resolved (it isn't): https://github.com/NevermindNilas/TheAnimeScripter/issues/20

I'm stuck with the default settings no matter what I change or try.

**Comment by NevermindNilas** [comment]
Hi,

I am pretty sure the issue was fixed back then but maybe the UI modifications I did in 1.8.2 have reintroduced them again.

In the meantime feel free to downgrade to 1.8.0 and try again.

**Comment by NevermindNilas** [comment]
Good to know.

**Comment by NevermindNilas** [comment]
Fixed with https://github.com/NevermindNilas/TheAnimeScripter/commit/5bf6424059766d3ea56238b1508612f78aa603b9
