### ISSUE TITLE
GUI: Add Command pane with read-only text box showing what command will be run when Run will be clicked / Add "Dry Run" option

### ISSUE THREAD

**Issue by przemoc** [NevermindNilas/TheAnimeScripter#37]
TAS GUI is effectively a relatively thin wrapper around `main` command-line tool, but still useful for newcomers. That's why I came up with idea to add Command pane (possibly between Options and Log, but anywhere will work, maybe it could be collapsaple/expandable by double-clicking or something like that) with read-only text box showing what command will be run when Run will be clicked. That way user does not have to click Run to learn what command will be executed.

Alternatively, "Dry Run" option could be added so that command would still go to Log upon clicking Run, but nothing else would be done (i.e. command would not be executed).

**Comment by NevermindNilas** [comment]
Oh that's sounds like a cool options, it will require some hackintoshing cuz the Standalone GUI is held together with hopes and prayers but it is something that's definitely noted.

**Comment by NevermindNilas** [comment]
Added a version 1.0 implementation of the idea with commit: https://github.com/NevermindNilas/TheAnimeScripter/commit/d5c6de510153ec18bb7a188404b63cf249608fe7

Thanks!
