### ISSUE TITLE
ffmpeg opening input files failed issue in TAS 1.9.9

### ISSUE THREAD

**Issue by GoldJohnKing** [NevermindNilas/TheAnimeScripter#50]
Hi, I get an issue in TAS 1.9.9 Release.

v1.9.4 and v1.9.7 is not affected by the issue.

![image](https://github.com/user-attachments/assets/9d242057-43f9-44d1-abc8-0c7bb7c9d227)

My command is as below:
``` bash
..\%tas_folder%\main.exe ^
--input %input_video% --output %output_video% ^
--upscale --upscale_factor %upscale_factor% --upscale_method span ^
--scenechange --scenechange_method maxxvit-tensorrt ^
--interpolate --interpolate_factor %interpolate_factor% --interpolate_method rife4.22-tensorrt ^
--encode_method nvenc_h265
```

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo

Password: changeme
I put the necessary dlls in the archive

**Comment by NevermindNilas** [comment]
Hi,

Did u rebuild all relevant engines? 

Also could you send `TAS.log`

**Comment by NevermindNilas** [comment]
Oh, nvm. I see where I messed up. Pushing a fix in a minute.

**Comment by NevermindNilas** [comment]
Fixed with: https://github.com/NevermindNilas/TheAnimeScripter/commit/f61f0ca1073544fd9ab4740f0422cfeeac54010a

Thanks
