### ISSUE TITLE
1.9.10 - 1440p (and higher) input source breaks TensorRT interpolation

### ISSUE THREAD

**Issue by volf3n** [NevermindNilas/TheAnimeScripter#51]
Excerpt from the log:
[log.txt](https://github.com/user-attachments/files/17235104/log.txt)
Command used:
`.\main.exe --input "{XYZ}" --interpolate --interpolate_factor 2 --interpolate_method rife4.22-tensorrt --custom_encoder="-c:v libsvtav1 -preset 8 -crf 20 -b:v 0 -pix_fmt yuv420p"`

**Comment by NevermindNilas** [comment]
Thanks, will look for a fix. 😭

**Comment by NevermindNilas** [comment]
Temp fix added for now, I will look to implement V1 Rife
