### ISSUE TITLE
White screen in after effects 2019

### ISSUE THREAD

**Issue by catoo-hub** [NevermindNilas/TheAnimeScripter#55]
Installation by extracting files to CEP/extentions
GPU: AMD RX5700XT, driver is 24.7.1
![image](https://github.com/user-attachments/assets/5107f2e7-5fa1-4eb9-9aac-ebce64277901)

**Comment by catoo-hub** [comment]
version of script is 1.9.10

**Comment by NevermindNilas** [comment]
Hi,

Which after effects are u using?

**Comment by NevermindNilas** [comment]
As per the readme.txt provided in the `.zip` folder.

```
Compatible with:
- Officially: Adobe 2022+ 
- Maybe?: Adobe 2020+
```

Sadly, your After Effects version is too old to be compatible with TAS. I'd suggest upgrading to 2022 or later.

**Comment by NevermindNilas** [comment]
Happy to help! :)
