### ISSUE TITLE
Encoding options

### ISSUE THREAD

**Issue by victorgt1** [NevermindNilas/TheAnimeScripter#56]
Hi, sorry if this is a noob question. But how do i change the x264 encoding settings from veryfast to slow in the adove version? is the a file I most edit? thank you

**Comment by NevermindNilas** [comment]
Hi,

In the main tab there should be a settings panel on the lower right side that opens up a dialog with settings one of which is a drop down for encoding related settings, scroll down and there is a " slow x264 " preset afaik which uses the preset "slow_x264" within TAS. 

There is currently no option and no plans for allowing the end user to decide their own encoding settings on the AE side for complexity reasons and user error related issues.
